<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2015/01/24 22:13:03
return array(

  // sfPropelPlugin_module_libs

  // sfI18NPlugin_module_libs

  // sfI18NPlugin_lib

  // sfConfigPlugin_module_libs

  // sfConfigPlugin_lib

  // sfAutoloadPlugin_module_libs
  'autoloadPlugin/mypluginssfautoloadpluginmodulesautoloadpluginlibclass' => '/Users/boutell/src/symfony1/test/functional/fixtures/plugins/sfAutoloadPlugin/modules/autoloadPlugin/lib/myPluginsSfAutoloadPluginModulesAutoloadPluginLib.class.php',

  // sfAutoloadPlugin_lib
  'baseextendme' => '/Users/boutell/src/symfony1/test/functional/fixtures/plugins/sfAutoloadPlugin/lib/BaseExtendMe.class.php',
  'extendme' => '/Users/boutell/src/symfony1/test/functional/fixtures/plugins/sfAutoloadPlugin/lib/ExtendMe.class.php',

  // not_in_lib_class
  'notinlib' => '/Users/boutell/src/symfony1/test/functional/fixtures/plugins/sfAutoloadPlugin/config/NotInLib.class.php',

  // sfPropelPlugin_lib
  'sfmixer' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => '/Users/boutell/src/symfony1/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'extendme' => '/Users/boutell/src/symfony1/test/functional/fixtures/lib/ExtendMe.class.php',
  'baseform' => '/Users/boutell/src/symfony1/test/functional/fixtures/lib/form/BaseForm.class.php',
  'mylibclass' => '/Users/boutell/src/symfony1/test/functional/fixtures/lib/myLibClass.class.php',

  // project_model

  // application
  'myappsfrontendlibclass' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/lib/myAppsFrontendLibClass.class.php',
  'myautoload' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/lib/myAutoload.class.php',
  'myautoloadedclass' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/lib/myAutoloadedClass.class.php',
  'myfilter' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/lib/myFilter.class.php',
  'myuser' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/lib/myUser.class.php',

  // modules
  'autoload/myappsfrontendmodulesautoloadlibclass' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/modules/autoload/lib/myAppsFrontendModulesAutoloadLib.class.php',
  'configFiltersSimpleFilter/configfilterssimplefilterfilter' => '/Users/boutell/src/symfony1/test/functional/fixtures/apps/frontend/modules/configFiltersSimpleFilter/lib/configFiltersSimpleFilterFilter.class.php',
);
